In [1]:
#Câu 1: Trong chương trình Python, viết 1 đoạn code tạo 1 nơ-ron với 3 ngõ vào, 3 trọng số tương ứng và 1 giá trị bias. Tính ngõ ra tương ứng và kiểm tra tính chính xác của gía trị ngõ ra.
# A single neuron with 3 inputs
input = [1, 2, 3]
weight = [0.2, 0.8, -0.5]
bias = 2
output = (input[0]*weight[0]+input[1]*weight[1]+input[2]*weight[2]+bias)
print(output)

2.3


In [38]:
# cau 2 
import numpy as np

inputs = np.array([1, 2, 3])

# random Gaussian (mean=0, var=1)
weights = np.random.randn(3)
bias = np.random.randn()

output = np.dot(inputs, weights) + bias

print("Weights:", weights)
print("Bias:", bias)
print("Output:", output)

Weights: [ 0.24927363  2.20009295 -2.39382941]
Bias: -0.927382535614372
Output: -3.459411246596982


In [4]:
import random
import numpy as np
class Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [ ]:
#cau3 
import numpy as np

inputs = np.array([1, 2, 3])
weights = np.array([0.2, 0.8, -0.5])
bias = 2

output = np.dot(inputs, weights) + bias

print("Output:", output)

In [ ]:
#cau 4

inputs = [1, 2, 3]

weights = [
    [0.2, 0.8, -0.5],
    [0.5, -0.91, 0.26],
    [-0.26, -0.27, 0.17]
]

bias = [2, 3, 0.5]

outputs = []

for neuron_weights, neuron_bias in zip(weights, bias):
    neuron_output = sum(i*w for i, w in zip(inputs, neuron_weights)) + neuron_bias
    outputs.append(neuron_output)

print("Outputs:", outputs)

In [ ]:
#cau 5
import numpy as np

inputs = np.array([1, 2, 3])

weights = np.array([
    [0.2, 0.8, -0.5],
    [0.5, -0.91, 0.26],
    [-0.26, -0.27, 0.17]
])

bias = np.array([2, 3, 0.5])

outputs = np.dot(weights, inputs) + bias

print("Outputs:", outputs)

[[-0.00559124  0.00028859 -0.00397988  0.00838675]]


In [ ]:
# cau 6 
import numpy as np

inputs = np.array([1, 2, 3, 2.5])

# Layer 1
weights1 = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
])

bias1 = np.array([2, 3, 0.5])

layer1_output = np.dot(weights1, inputs) + bias1

# Layer 2
weights2 = np.array([
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]
])

bias2 = np.array([-1, 2, -0.5])

layer2_output = np.dot(weights2, layer1_output) + bias2

print("Final output:", layer2_output)

[[-0.90730308  0.35662539 -0.74140782]]
[[ 0.02326166 -0.01285523 -0.01729971]]


In [ ]:
# cau 7
inputs = np.array([
    [1, 2, 3, 2.5],
    [2, 5, -1, 2],
    [-1.5, 2.7, 3.3, -0.8]
])

outputs = np.dot(inputs, weights1.T) + bias1

print(outputs)

In [ ]:
#cau 8 
import numpy as np

class Dense_Layer:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [ ]:
#cau 9
layer1 = Dense_Layer(4, 3)

inputs = np.array([
    [1, 2, 3, 2.5]
])

layer1.forward(inputs)

print(layer1.output)

In [ ]:
# cau 10 
layer1 = Dense_Layer(4, 3)
layer2 = Dense_Layer(3, 3)

inputs = np.array([
    [1, 2, 3, 2.5]
])

layer1.forward(inputs)
layer2.forward(layer1.output)

print("Final output:", layer2.output)